## 1. 创建超级用户失败

##### 报错

```python
python manage.py createsuperuser

报错：django.db.utils.ProgrammingError: ("Table 'xxxx.auth_user' doesn't exist")
```

##### 原因

createsuperuser时django的后台管理也会相应创建一些表，其中auth_user就是后台管理用户需要使用的表，createsuperuser时会寻找相关表，找不到就会异常；

##### 解决方法

在pycharm的Terminal输入：

```python
python manage.py makemigrations    
#再次生成数据库迁移文件

python manage.py migrate           
#再次执行数据迁移文件，补偿性创建缺失的表

python manage.py createsuperuser   
#再次创建用户
```

##### 后续跟进

此方法可能如果还不能解决问题，建议这样排查：

1、登陆数据，查看是否缺失报错提示的表，如果确实缺失，然后在再次执行python manage.py makemigrations 和python manage.py migrate 时提示你没有任何更改，可以尝试删除应用下migrations中生成的文件；

2、登陆数据库查看select * from django_migrations; 查看所有执行记录，删除最后的执记录；

3、然后思考下，当前使用的数据库是不是和之前其它django项目使用的是同一个数据库，（此情况极有可能是之前的dajngo项目使用这个数据时自定义了admin中表，导致创建的表名和当前项目auth_user不匹配，在执行迁移文件时候django看到库中已经有了用户组的表，所以就不创建了，当使用时候按照新项目寻找新的管理用户的表，表不存在抛出来的异常），这时候建议在这个数据库中删除创建超级用户之前本项目创建生成的表，然后settings中的database部分换一个没有django项目使用的数据库：

4、如果不采用上述方案，依旧想和其它django项目使用同一个数据库，那在admin定义上必须和原django项目保持一致；或者直接可以尝试使用那个项目的超级用户登陆admin，因为本质上两个django项目使用的同一个数据库，管理面使用的用户在表中是已经存在过的；（此方案暂时未验证，慎用）